version: '3'

services:
  db:
    image: postgres
    environment:
      POSTGRES_DB: stock_db
      POSTGRES_USER: your_user
      POSTGRES_PASSWORD: your_password
    volumes:
      - postgres_data:/var/lib/postgresql/data

  stock_service:  # Renamed from 'web' to 'stock_service'
    build: ./stock_service
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./stock_service:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - POSTGRES_DB=stock_db
      - POSTGRES_USER=your_user
      - POSTGRES_PASSWORD=your_password

volumes:
  postgres_data:
